### ISSUE TITLE
Piper is missing on Flathub.org?

### ISSUE THREAD

**Issue by LeandroStanger** [flathub/org.freedesktop.Piper#1]
The Piper page is missing on the Flathub website and the Flatpak is also missing in GNOME Software. It looks like that there is some issue with the AppStream metadata.
![captura de tela de 2018-09-07 19-53-55](https://user-images.githubusercontent.com/26097419/45246460-ca818a00-b2d7-11e8-8c03-984b7d9e9e33.png)

**Comment by whot** [comment]
well, that got closed faster than expected... either way, I thought the issue was the 16:9 screenshots which I have uploaded now to the piper wiki, PR is filed too. Pushing 47cda658ca6bf9698ea made no difference though, still not found...

**Comment by Hjdskes** [comment]
My other application on Flathub also does not have 16:9 screenshots but shows up just fine: https://flathub.org/apps/details/nl.hjdskes.gcolor3

I don't think this is something in the AppData. @TingPing (or someone else on the Flathub team) can you see what is going wrong somewhere?

**Comment by jgarciao** [comment]
I think the problem is that there is not <icon> in the appstream file for this app

More info [here](https://github.com/flathub/com.adobe.Flash-Player-Projector/issues/2#issuecomment-419870858)

**Comment by whot** [comment]
Hooray, this did the trick, piper is now on flathub!

https://flathub.org/apps/details/org.freedesktop.Piper

**Comment by hadess** [comment]
I filed a bug to have appstream-compose fail with the same requirements as Flathub:
https://github.com/hughsie/appstream-glib/issues/263
