### ISSUE TITLE
Piper flatpak does not open ubuntu 18.04

### ISSUE THREAD

**Issue by chui2ch** [flathub/org.freedesktop.Piper#2]
I install libratbag4 and ratbagd when I launch Piper nothing happens. Here is my terminal output.
```
No active profile. Please report this bug to the libratbag developers
Traceback (most recent call last):
  File "/app/lib/python3.5/site-packages/piper/application.py", line 52, in do_activate
    window = Window(self._ratbag, application=self)
  File "/app/lib/python3.5/site-packages/piper/window.py", line 67, in __init__
    self._present_mouse_perspective(ratbag.devices[0])
  File "/app/lib/python3.5/site-packages/piper/window.py", line 150, in _present_mouse_perspective
    mouse_perspective.set_device(device)
  File "/app/lib/python3.5/site-packages/piper/mouseperspective.py", line 96, in set_device
    self.label_profile.set_label(active_profile.name)
TypeError: Argument 1 does not allow None as a value
```

**Comment by Hjdskes** [comment]
Can you try installing libratbag from git? You can find how to do this in the [README](https://github.com/libratbag/libratbag/blob/master/README.md).

**Comment by chui2ch** [comment]
Thanks for the suggestion. I understand that the version of libratbag in Ubuntu 18.04 may not be compatible with piper, but building libratbag from source defeats the purpose of using the piper flatpak for me.

**Comment by Hjdskes** [comment]
Yes, the situation is a little clumsy at the moment. Apologies for that. Out of interest for your issue though, did using the git version solve your problem? If not, we should definitely look into that.

**Comment by chui2ch** [comment]
It does launch if I am using the git version of libratbag.

**Comment by Hjdskes** [comment]
Great, thanks for testing!

**Comment by Hjdskes** [comment]
Great, thanks for testing!
