### ISSUE TITLE
Piper 0.3 is not working

### ISSUE THREAD

**Issue by Cris70** [flathub/org.freedesktop.Piper#6]
Piper reports "incompatible ratbagd API version" upon launch.
Reason is [explained here](https://github.com/libratbag/piper/issues/379).
Flatpak should be rebuilt.

**Comment by whot** [comment]
rebuilding the flatpak won't make a difference here since the supported version is hardcoded in piper, I suspect this is a local issue or an issue with the repos you're using. Either way, let's deal with that in one issue tracker only please.
